[package]
name = "rwgrc"
version = "0.1.0"
authors = ["Cody P Schafer <dev@codyps.com>"]
edition = "2018"

[dependencies]
tonic = "0.2"
prost = "0.6"
tokio = { version = "1.8", features = ["macros"] }
rand = "0.7"
log = "*"
env_logger = "*"

[build-dependencies]
tonic-build = "0.2"
